[images]
remote_images = [
  "^(?:https:\\/(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:http:\\/(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
]

# 新增全局 headers 配置
[[headers]]
for = "/*"  # 应用于所有路径
  [headers.values]
  # 明确忽略查询参数对缓存的影响
  Cache-Control = "public, max-age=0, must-revalidate"
  # 确保不根据查询参数改变缓存（移除或覆盖 Vary: query）
  Vary = "Accept-Encoding"

[[headers]]
for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=7776000, immutable"  # 改为 3 个月

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[context]
  [context.production]
    [context.production.images]
    remote_images = [
      "^(?:https:\\/(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http:\\/(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

    [[context.production.headers]]
    for = "/_next/static/*"
      [context.production.headers.values]
      Cache-Control = "public, max-age=7776000, immutable"  # 改为 3 个月

  [context.main]
    [context.main.images]
    remote_images = [
      "^(?:https:\\/(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http:\\/(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

    [[context.main.headers]]
    for = "/_next/static/*"
      [context.main.headers.values]
      Cache-Control = "public, max-age=7776000, immutable"  # 改为 3 个月
